#!/command/with-contenv sh

TIMESTAMP_FILE=/etc/init_useradd
if [ -e $TIMESTAMP_FILE ]; then
    exit 0
fi
touch $TIMESTAMP_FILE



if [ "$DEBUG" = "1" ] || [ "$DEBUG" = "TRUE" ] || [ "$DEBUG" = "true" ]; then
    minijinja-cli /etc/templates/useradd.sh.j2 \
        -D DEBUG="${DEBUG}"   \
        -D groups:="${INIT_GROUPS}"   \
        -D users:="${INIT_USERS}"   \
        -D create_dirs:="${INIT_CREATE_DIRS}" \
        | tee | bash -
else
    minijinja-cli /etc/templates/useradd.sh.j2 \
        -D groups:="${INIT_GROUPS}"   \
        -D users:="${INIT_USERS}"   \
        -D create_dirs:="${INIT_CREATE_DIRS}" \
        | bash -
fi

