#!/command/with-contenv bash
set -e
TIMESTAMP_FILE=/config/init_sshd_config
SSHD_CONFIG_PATH="/config/sshd_config"

if [ "$DEBUG" = "1" ] || [ "$DEBUG" = "TRUE" ] || [ "$DEBUG" = "true" ]; then
    DEBUG_ON=1
    set -x
else
    DEBUG_ON=0
fi

if [ -e $TIMESTAMP_FILE ]; then
    exit 0
fi
touch $TIMESTAMP_FILE

# Make sure /config directory exists
if [ ! -d /config  ]; then
    mkdir -p /config
fi
chmod 755 /config

#  Generate host keys if they do not exist
for t in rsa ecdsa ed25519; do
    key="/config/ssh_host_${t}_key"
    if [ ! -f "$key" ]; then
        ssh-keygen -t "$t" -f "$key" -N '' -q || exit $?
        chmod 600 "$key"
        [ -f "${key}.pub" ] && chmod 644 "${key}.pub"
    fi
done


CMD=(minijinja-cli -D DEBUG="${DEBUG}")

if [ -n "${INIT_CONFIG:-}" ]; then
    if [ -f "${INIT_CONFIG}" ]; then
        CMD+=("/etc/templates/sshd_config.j2" "${INIT_CONFIG}")
    else
        echo "WARNING: INIT_CONFIG is set but the file does not exist: ${INIT_CONFIG}"
        exit 1
    fi
else
    CMD+=(-D "sshd_config:=${INIT_SSHD_CONFIG}" "/etc/templates/sshd_config.j2")
fi

if [ "$DEBUG_ON" -eq 1 ]; then
    "${CMD[@]}" | tee $SSHD_CONFIG_PATH
else
    "${CMD[@]}" > $SSHD_CONFIG_PATH
fi

# if [ -n "${INIT_CONFIG}" ]; then
#     if [ -f "${INIT_CONFIG}" ]; then
#         minijinja-cli \
#             -D DEBUG="${DEBUG}" \
#             /etc/templates/sshd_config.j2 \
#             ${INIT_CONFIG} | $OUTPUT
#     else
#         echo "WARNING: INIT_CONFIG is set but the file does not exist: ${INIT_CONFIG}"
#         exit 1
#     fi
# else
#     minijinja-cli \
#         -D DEBUG="${DEBUG}" \
#         -D sshd_config:="${INIT_SSHD_CONFIG}" \
#          /etc/templates/sshd_config.j2 \
#          | "$OUTPUT"
# fi