#!/command/with-contenv bash

if [ "$DEBUG" = "1" ] || [ "$DEBUG" = "TRUE" ] || [ "$DEBUG" = "true" ]; then
    DEBUG_ON=1
    set -x
else
    DEBUG_ON=0
fi

TIMESTAMP_FILE=/etc/init_sshd_config
if [ -e $TIMESTAMP_FILE ]; then
    exit 0
fi
touch $TIMESTAMP_FILE


if [ ! -d /etc/ssh  ]; then
    mkdir -p /etc/ssh
    chmod 755 /etc/ssh
fi

CMD=(minijinja-cli -D DEBUG="${DEBUG}")

if [ -n "${INIT_CONFIG:-}" ]; then
    if [ -f "${INIT_CONFIG}" ]; then
        CMD+=("/etc/templates/sshd_config.j2" "${INIT_CONFIG}")
    else
        echo "WARNING: INIT_CONFIG is set but the file does not exist: ${INIT_CONFIG}"
        exit 1
    fi
else
    CMD+=(-D "sshd_config:=${INIT_SSHD_CONFIG}" "/etc/templates/sshd_config.j2")
fi

if [ "$DEBUG_ON" -eq 1 ]; then
    "${CMD[@]}" | tee /etc/ssh/sshd_config
else
    "${CMD[@]}" > /etc/ssh/sshd_config
fi

# if [ -n "${INIT_CONFIG}" ]; then
#     if [ -f "${INIT_CONFIG}" ]; then
#         minijinja-cli \
#             -D DEBUG="${DEBUG}" \
#             /etc/templates/sshd_config.j2 \
#             ${INIT_CONFIG} | $OUTPUT
#     else
#         echo "WARNING: INIT_CONFIG is set but the file does not exist: ${INIT_CONFIG}"
#         exit 1
#     fi
# else
#     minijinja-cli \
#         -D DEBUG="${DEBUG}" \
#         -D sshd_config:="${INIT_SSHD_CONFIG}" \
#          /etc/templates/sshd_config.j2 \
#          | "$OUTPUT"
# fi